name = "MyrMod v4";          // Name of your mod
author = "MyrMod Team";      // Affects Arma 3 Launcher, when the mod are loaded as local
logo = "myrarsenal.paa";     // Logo displayed in the main menu
logoOver = "myrarsenal.paa"; // When the mouse is over, in the main menu
tooltip = "MyrMod";
tooltipOwned = "MyrMod";    // Tool tip displayed when the mouse is left over, in the main menu
picture = "myrarsenal.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName = "UnitPage";
action = "";                                                                                                                                                                                                                                          // Website URL, that can be accessed from the expansions menu
overview = "This is an auxiliary mod that *REDACTED* uses so that we can have our own custom textures and modified values to existing assets. We take no claim over the creation of any assets just simply changing values of things to our liking."; // Supports structured text
logoSmall = "myrarsenal.paa";                                                                                                                                                                                                                         // Display in creative lists, next to the entities added by the mod