//-----------Load Outs-----------//

_allLoadOuts = [

//-----Myrmidon TL-----//
["Team Leader", [["JCA_arifle_M4A4_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AICO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1],["ACE_DefusalKit",1],["MineDetector",1]]],["Myr_Grey_Command",[["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_AED",1],["kat_Painkiller",2,4]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmiodon Contractor-----//
["Contractor", [["JCA_arifle_M4A4_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],[],""],["tf47_at4_heat","","","",[],[],""],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Combat",[["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["HandGrenade",5,1],["ACE_M84",5,1],["SmokeShell",10,1]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Grenadier-----//
["Grenadier", [["JCA_arifle_M4A4_GL_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],["1Rnd_HE_Grenade_shell",1],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1],["ACE_HuntIR_monitor",1]]],["Myr_Grey_Combat",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["1Rnd_HEDP_Grenade_shell",10,1],["1Rnd_HE_Grenade_shell",15,1],["ACE_HuntIR_M203",5,1],["UGL_FlareRed_F",5,1],["UGL_FlareWhite_F",15,1],["ACE_40mm_Flare_white",5,1]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Marksman-----//
["Marksman", [["JCA_arifle_SR10_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AICO_black",["JCA_20Rnd_762x51_PMAG",20],[],"JCA_bipod_04_black"],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Recon",[["JCA_17Rnd_9x21_P320_Green_Mag",1,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_20Rnd_762x51_Green_PMAG",7,20]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["ACE_Tripod",1],["ACE_SpottingScope",1],["ACE_RangeCard",1],["kat_Painkiller",2,4],["JCA_20Rnd_762x51_Green_PMAG",2,20]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Sniper-----//
["Sniper", [["JCA_srifle_AWM_black_F","JCA_muzzle_snds_AWM_tactical_black","","JCA_optic_HPPO_RAD_black",["JCA_5Rnd_338LM_Mag",5],[],"JCA_bipod_AWM_black"],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Recon",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_5Rnd_338LM_Mag",7,5]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["ACE_Tripod",1],["ACE_SpottingScope",1],["ACE_RangeCard",1],["kat_Painkiller",2,4],["JCA_5Rnd_338LM_Mag",2,5]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Autorifleman-----//
["Autorifleman", [["LMG_Mk200_black_F","","JCA_acc_LaserModule_black_Pointer","JCA_optic_AHO_black",["200Rnd_65x39_cased_Box",200],[],"JCA_bipod_04_black"],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Tactical",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["200Rnd_65x39_cased_Box",1,200]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["200Rnd_65x39_cased_Box",2,200]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Breacher Shotgun-----//
["Breacher (Shotgun)", [["sgun_M4_F","","","E22_optic_ROS_black_SMG",["8Rnd_12Gauge_Pellets",8],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Heavy",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["8Rnd_12Gauge_Pellets",5,8]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["8Rnd_12Gauge_Slug",7,8],["Aegis_8Rnd_12Gauge_Smoke",2,8],["8Rnd_12Gauge_Pellets",2,8]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Breacher SMG-----//
["Breacher (SMG)", [["JCA_smg_MP5_VFG_black_F","","JCA_acc_LaserModule_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",30],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Heavy",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",6,30]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",6,30]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon EOD-----//
["EOD", [["JCA_arifle_M4A4_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ItemAndroid",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1],["MineDetector",1],["ACE_M26_Clacker",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1]]],["Myr_Grey_Combat",[["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["ToolKit",1],["kat_Painkiller",2,4],["SatchelCharge_Remote_Mag",1,1],["DemoCharge_Remote_Mag",2,1],["SLAMDirectionalMine_Wire_Mag",2,1]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Medic-----//
["Medic", [["JCA_arifle_M4A4_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Combat",[["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1]]],["Myr_M9_Grey",[["ACE_adenosine",3],["ACE_elasticBandage",40],["ACE_packingBandage",40],["ACE_bodyBag_blue",1],["kat_chestSeal",10],["kat_accuvac",1],["kat_X_AED",1],["kat_IV_16",15],["kat_atropine",2],["kat_amiodarone",5],["kat_bloodIV_O_N",4],["kat_bloodIV_O_N_500",6],["kat_bloodIV_O_N_250",4],["kat_IO_FAST",4],["kat_fentanyl",5],["KAT_Empty_bloodIV_500",2],["kat_epinephrineIV",10],["kat_larynx",10],["kat_naloxone",2],["kat_ncdKit",5],["kat_norepinephrine",5],["kat_Pulseoximeter",1],["ACE_splint",5],["ACE_tourniquet",6],["kat_TXA",10],["kat_stethoscope",1],["kat_BVM",1],["kat_oxygenTank_150",1,100]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Antitank-----//
["Antitank", [["JCA_arifle_M4A4_VFG_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AICO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],[],""],["launch_Titan_short_blk_F","","","",["Titan_AT",1],[],""],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Combat",[["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30],["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1]]],["Myr_Fastbag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["kat_Painkiller",2,4],["Titan_AT",2,1]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon JTAC-----//
["JTAC", [["JCA_arifle_M4A4_GL_black_F","","JCA_acc_DualMount_black_Pointer","JCA_optic_AICO_black",["JCA_30Rnd_556x45_Tracer_Green_PMAG",30],["1Rnd_RC40_shell_RF",1],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Grey_Rolled",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Command",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_30Rnd_556x45_Tracer_Green_PMAG",10,30]]],["Myr_Radiobag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["MRH_FoldedSatcomAntenna",1],["MRH_TacticalDisplay",1],["kat_Painkiller",2,4],["1Rnd_RC40_HE_shell_RF",10,1],["1Rnd_RC40_shell_RF",5,1]]],"Myr_Helmet_Tan","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]],

//-----Myrmidon Pilot-----//
["Pilot", [["JCA_smg_MP5_VFG_black_F","","JCA_acc_LaserModule_black_Pointer","JCA_optic_AHO_black",["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",30],[],""],[],["JCA_hgun_P320_black_F","","JCA_acc_LightModule_Pistol_black","JCA_optic_PRO_black",["JCA_17Rnd_9x21_P320_Green_Mag",17],[],""],["Myr_Pilot_Coveralls",[["ACE_wirecutter",1],["ItemAndroid",1],["ACE_EntrenchingTool",1],["ACE_CableTie",5],["ACE_IR_Strobe_Item",3],["ACE_Flashlight_MX991",1]]],["Myr_Grey_Compact",[["JCA_17Rnd_9x21_P320_Green_Mag",2,17],["SmokeShell",5,1],["JCA_SignalFlare_Green",1,1],["HandGrenade",2,1],["ACE_M84",2,1],["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",6,30]]],["Myr_Radiobag_Blk",[["ACE_adenosine",3],["ACE_elasticBandage",10],["ACE_packingBandage",10],["ACE_bodyBag_blue",1],["ACE_tourniquet",4],["ACE_splint",2],["kat_bloodIV_O_N_250",1],["kat_guedel",1],["kat_chestSeal",2],["kat_Pulseoximeter",1],["ACE_morphine",1],["ACE_epinephrine",2],["ToolKit",1],["kat_Painkiller",2,4],["JCA_30Rnd_9x21_MP5_Tracer_Green_Mag",6,30]]],"Myr_Pilot_Helmet_Up","E22_G_Shemagh_light_black_F",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]]

];

//----------LoadOuts End----------//
// to add new line ["79th XXX", (Paste from beginning to just after nvg)]
//-------add loadouts to ace default loadouts------//
{[_x select 0,_x select 1] call ace_arsenal_fnc_addDefaultLoadout} forEach _allLoadOuts;
